### ISSUE TITLE
license

### ISSUE THREAD

**Issue by nean-and-i** [DabblerDK/MEP-SW-ESP32#5]
Hi Gert, 

despite the question in the OSGP board regarding the digest reference implementation source code, under which license is the rest of the project ?
Will it be under a OpenSource license or under copyright?

thanks

**Comment by glynge** [comment]
The hard- and software created solely by us is 100% free for any use (even commercial), but we will not be held liable of any damage/issues/looses etc. caused by it. All use is on your own risk/costs.

We do not have any distribution rights to any other parts of the used source code/components/libraries (i.e. parts not solely created by us - like the digest function, libraries and some web components), so you need to investigate if your planned usage of the hard- and software is within the license of those parts.
.
We also kindly ask you, but does NOT require you, to refer and keep any references to our www.dabbler.dk webpage...
